Create converter and test
AliceTrinta/fornecedor-de-jogos pull request #6
Opened 2023-06-05 22:46 UTC by miguelthemigs

2023-06-05 22:57 UTC, AliceTrinta requested changes

2023-06-05 22:57 UTC, AliceTrinta commented on tests/converter/converter_test.py
> +    assert game_df.equals(game_df)
Aqui ainda entendo que vc ta comparando a mesma variavel, pode colocar nomes diferentes? ate pra manter o padrão por todos os testes da aplicação (expected X result)

2023-06-05 22:57 UTC, AliceTrinta commented on tests/converter/converter_test.py
>  def test_xml_to_game():
Falta o teste da game_to_xml?

2023-06-05 23:01 UTC, AliceTrinta commented on tests/converter/converter_test.py
> +    assert game_df.equals(game_df)
O comentário vale tb pro outro teste

2023-06-05 23:05 UTC, miguelthemigs commented on tests/converter/converter_test.py
> +    assert game_df.equals(game_df)
ahh tranquilo

2023-06-05 23:27 UTC, miguelthemigs commented
agora achp que esta tudo certo

2023-06-06 01:35 UTC, AliceTrinta submitted a review, later dismissed

2023-06-06 01:35 UTC, AliceTrinta commented on tests/converter/converter_test.py
>  def test_xml_to_game():
Da uma olhada nesse [PR](https://github.com/AliceTrinta/fornecedor-de-jogos/pull/7/files) e tenta seguir esse formato nesses testes.

2023-06-06 13:10 UTC, miguelthemigs commented on tests/converter/converter_test.py
>  def test_xml_to_game():
falta fazer entao testes quando o xml é nulo?

2023-06-06 14:27 UTC, miguelthemigs commented
adicionado testes restantes

2023-06-06 15:02 UTC, AliceTrinta requested changes

2023-06-06 15:02 UTC, AliceTrinta commented on src/converter/converter.py
> +        index_element = root.find('row/index')
precisa do index?

2023-06-06 15:02 UTC, AliceTrinta commented on src/converter/converter.py
> +    if game_data is None or game_data.empty:
Aqui a gente não precisa dessa verificação, pq como trabalhamos o dataframe internamente, ele nunca vai estar incorreto. Já quando recebemos o XML, como vem do cliente ai sim pode vir num formato incorreto ou sl.

2023-06-06 15:02 UTC, AliceTrinta commented on src/converter/converter.py
> +    if game_data is None or game_data.empty:
Aqui ent é só transformar mesmo.

2023-06-06 15:02 UTC, AliceTrinta commented on tests/converter/converter_test.py
>  def test_xml_to_game():
Não só o caso que faltava mas o padrão de comentário, nomeclatura nos asserts e nomenclatura nos testes. se n mantivermos esse padrão por todos os testes o professor vai tirar ponto, como ele mesmo disse. se quiser modificar o padrão que está sendo tomando da uma olhada no PR citado e manda no grupo. Eu me baseei mto naquele primeiro file de de dataframe do gruilherme.

2023-06-06 15:56 UTC, miguelthemigs commented on src/converter/converter.py
> +        index_element = root.find('row/index')
O index é criado a partir do data frame, não como um parametro noss. Por padrao, os dfs tem index, o que eu nao consigo tirar. No game_data = game_data.drop(columns=['index']) eu retorno sem o index, mas na passagem de valores por xml, pode passar sem index, pois o df gera automaticamente.

2023-06-06 16:00 UTC, miguelthemigs commented
mudei as coisas

2023-06-06 16:38 UTC, AliceTrinta requested changes

2023-06-06 16:38 UTC, AliceTrinta commented on src/converter/converter.py
> +    if len(game_data.columns) != 3:
Não precisa da verificação aqui, pq pra chegar um dataframe pra essa função, 100% de certeza que ele é valido. Eu n vejo pelo menos caso onde possa chegar diferente.

2023-06-06 16:38 UTC, AliceTrinta commented on src/converter/converter.py
> +            game_data = game_data.drop(columns=['index'])
Pq está dropando o index?

2023-06-06 21:15 UTC, miguelthemigs commented on src/converter/converter.py
> +            game_data = game_data.drop(columns=['index'])
pq o dataframe tem um index por padrao, e devo dropar ele para n'ao ficar repetido. Se eu n'ao dropo, o teste nao funciona

2023-06-06 21:15 UTC, miguelthemigs commented on src/converter/converter.py
> +    if len(game_data.columns) != 3:
nem um dataframe que a pessoa esqueceu de colocar uma categoria?

2023-06-25 20:25 UTC, AliceTrinta approved these changes

2023-06-25 20:25 UTC, merged